### ISSUE TITLE
Data source and dates of Speeches?

### ISSUE THREAD

**Issue by KrbAlmryde** [ryanmcdermott/trump-speeches#2]
Hi, 

This is really cool, thanks for putting it together. Can you add or provide a source for this data and how you obtained/compiled it? 

Also, does each line represent an individual speech, or can speeches occupy multiple lines etc. 

Finally, when and where do these speeches occur? Which one was given in say Virgina and Texas etc. 

Thank you

**Comment by ryanmcdermott** [comment]
Addressed in #3 😄
